# Reading Data from various data source using Pandas

## Reading JSON Data into a DataFrame

In [2]:
import pandas as pd 
from io import StringIO
Data = '{"employee_name": "Rohit", "email": "rohitsharma45@gmail.com", "job_profile": [{"title1": "Captain", "title2": "Show Host"}]}'
df = pd.read_json(StringIO(Data))

In [3]:
df

,employee_name,email,job_profile
0,Rohit,rohitsharma45@gmail.com,"{'title1': 'Captain', 'title2': 'Show Host'}"

### Converting DataFrame to JSON

In [4]:
df.to_json()

'{"employee_name":{"0":"Rohit"},"email":{"0":"rohitsharma45@gmail.com"},"job_profile":{"0":{"title1":"Captain","title2":"Show Host"}}}'

### Converting DataFrame to JSON Using Index Orientation

In [5]:
df.to_json(orient='index')

'{"0":{"employee_name":"Rohit","email":"rohitsharma45@gmail.com","job_profile":{"title1":"Captain","title2":"Show Host"}}}'

### Converting DataFrame to JSON Using Records Orientation

In [6]:
df.to_json(orient='records')

'[{"employee_name":"Rohit","email":"rohitsharma45@gmail.com","job_profile":{"title1":"Captain","title2":"Show Host"}}]'

## Reading CSV Data from a URL

In [7]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)

In [8]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [9]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

### Saving DataFrame to a CSV File

In [10]:
df.to_csv("wine.csv")

## Reading HTML Tables from a Web Page

In [11]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list"
df = pd.read_html(url)

In [12]:
df

[                                          Bank Name               City  \
 0                       Tioga-Franklin Savings Bank       Philadelphia
 1                               Small Business Bank             Lenexa
 2     Kentland Federal Savings and Loan Association           Kentland
 3           Community Bank and Trust - West Georgia           LaGrange
 4                 Metropolitan Capital Bank & Trust            Chicago
 5                      The Santa Anna National Bank         Santa Anna
 6                              Pulaski Savings Bank            Chicago
 7                The First National Bank of Lindsay            Lindsay
 8             Republic First Bank dba Republic Bank       Philadelphia
 9                                     Citizens Bank           Sac City
 10                         Heartland Tri-State Bank            Elkhart
 11                              First Republic Bank      San Francisco
 12                                   Signature Bank           New York
 13                              Silicon Valley Bank        Santa Clara
 14                                Almena State Bank             Almena
 15                       First City Bank of Florida  Fort Walton Beach
 16                             The First State Bank      Barboursville
 17                               Ericson State Bank            Ericson
 18                 City National Bank of New Jersey             Newark
 19                                    Resolute Bank             Maumee
 20                            Louisa Community Bank             Louisa
 21                             The Enloe State Bank             Cooper
 22              Washington Federal Bank for Savings            Chicago
 23  The Farmers and Merchants State Bank of Argonia            Argonia
 24                              Fayette County Bank         Saint Elmo

             State   Cert                              Acquiring Institution  \
 0    Pennsylvania  33802  Second Federal Savings and Loan Association of...
 1          Kansas  25744           The Farmers State Bank of Oakley, Kansas
 2         Indiana  28722                                      Kentland Bank
 3         Georgia  25796                                        Anchor Bank
 4        Illinois  57488                            First Independence Bank
 5           Texas   5520                          Coleman County State Bank
 6        Illinois  28611                                    Millennium Bank
 7        Oklahoma   4134                             First Bank & Trust Co.
 8    Pennsylvania  27332                  Fulton Bank, National Association
 9            Iowa   8758                          Iowa Trust & Savings Bank
 10         Kansas  25851                             Dream First Bank, N.A.
 11     California  59017                          JPMorgan Chase Bank, N.A.
 12       New York  57053                                Flagstar Bank, N.A.
 13     California  24735                First–Citizens Bank & Trust Company
 14         Kansas  15426                                        Equity Bank
 15        Florida  16748                          United Fidelity Bank, fsb
 16  West Virginia  14361                                     MVB Bank, Inc.
 17       Nebraska  18265                         Farmers and Merchants Bank
 18     New Jersey  21111                                    Industrial Bank
 19           Ohio  58317                                 Buckeye State Bank
 20       Kentucky  58112                  Kentucky Farmers Bank Corporation
 21          Texas  10716                                 Legend Bank, N. A.
 22       Illinois  30570                                 Royal Savings Bank
 23         Kansas  17719                                        Conway Bank
 24       Illinois   1802                          United Fidelity Bank, fsb

          Closing Date  Fund  Sort ascending
 0     August 21, 2026                 10554
 1       July 17, 2026                 10553
 2       July 10, 2026                 10552
 3         May 1, 2026                 10551
 4    January 30, 2026                 10550
 5       June 27, 2025                 10549
 6    January 17, 2025                 10548
 7    October 18, 2024                 10547
 8      April 26, 2024                 10546
 9    November 3, 2023                 10545
 10      July 28, 2023                 10544
 11        May 1, 2023                 10543
 12     March 12, 2023                 10540
 13     March 10, 2023                 10539
 14   October 23, 2020                 10538
 15   October 16, 2020                 10537
 16      April 3, 2020                 10536
 17  February 14, 2020                 10535
 18   November 1, 2019                 10534
 19   October 25, 2019                 10533
 20   October 25, 2019                 10532
 21       May 31, 2019                 10531
 22  December 15, 2017                 10530
 23   October 13, 2017                 10529
 24       May 26, 2017                 10528  ]

## Reading HTML Tables from Wikipedia

In [13]:
url3 = "https://en.wikipedia.org/wiki/Mobile_country_code"

tables = pd.read_html(
    url3,
    storage_options={"User-Agent": "Mozilla/5.0"}
)

print(tables)

[   MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any
1    1    1  TEST  Test network  Operational         any
2  999   99   NaN  Internal use  Operational         any
3  999  999   NaN  Internal use  Operational         any

                              References and notes
0                                              NaN
1                                              NaN
2  Internal use in private networks, no roaming[6]
3  Internal use in private networks, no roaming[6]  ,      Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB
1                    412                                Afghanistan       AF
2                    276                                    Albania       AL
3                    603                                    Algeria       DZ
4                    544  American Samoa (United States of America)       AS
..                   ...                                        ...      ...
247                  452                                    Vietnam       VN
248                  543                        W Wallis and Futuna       WF
249                  421                                    Y Yemen       YE
250                  645                                   Z Zambia       ZM
251                  648                                   Zimbabwe       ZW

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN
1          List of mobile network codes in Afghanistan                    NaN
2              List of mobile network codes in Albania                    NaN
3              List of mobile network codes in Algeria                    NaN
4       List of mobile network codes in American Samoa                    NaN
..                                                 ...                    ...
247        List of mobile network codes in the Vietnam                    NaN
248  List of mobile network codes in Wallis and Futuna                    NaN
249          List of mobile network codes in the Yemen                    NaN
250             List of mobile network codes in Zambia                    NaN
251           List of mobile network codes in Zimbabwe                    NaN

                      Remarks
0    MCC is not listed by ITU
1                         NaN
2                         NaN
3                         NaN
4                         NaN
..                        ...
247                       NaN
248                       NaN
249                       NaN
250                       NaN
251                       NaN

[252 rows x 6 columns],      MCC  MNC     Brand                  Operator           Status  \
0    901    1       NaN                   Webbing          Unknown
1    901    2       NaN            GlobalmatiX AG          Unknown
2    901    3   Iridium                       NaN      Operational
3    901    4       NaN  BBIX Singapore Pte. Ltd.          Unknown
4    901    5       NaN      Thuraya RMSS Network      Operational
..   ...  ...       ...                       ...              ...
99   902    1       NaN        MulteFire Alliance      Operational
100  991    1       NaN    World's Global Telecom  Not operational
101  991    2  5G Croco               Orange S.A.  Not operational
102  991    3       NaN                 Halys SAS  Not operational
103  991    4       NaN              E-Space Inc.          Unknown

    Bands (MHz)                               References and notes
0          MVNO            Former ICO Satellite Management[51][52]
1       Unknown  Former Sense Communications International; veh...
2     Satellite                                                NaN
3       Unknown                              Former Globalstar[54]
4     Satellite                                                NaN
..          ...                                                ...
99          LTE                                           [6][134]
100     Unknown  temporarily assigned until 15 January 2021[110...
101          5G  temporarily assigned until 6 August 2022[136][...
102     Unknown  temporary assignment for trial until 5 April 2...
103   Satellite  temporary assignment for trial until 17 Oct 20...

[104 rows x 7 columns],    MCC  MNC     Brand                 Operator       Status Bands (MHz)  \
0  995    1  FonePlus  Sure (Diego Garcia) Ltd  Operational     GSM 900

                                References and notes
0  There appears to be no officially assigned MCC...  ,                                vteTelecommunications  \
0                                            History
1                                           Pioneers
2                                 Transmission media
3                     Network topology and switching
4                                       Multiplexing
5                                           Concepts
6                                   Types of network
7                                   Notable networks
8                                          Locations
9  Telecommunication portal  Category  Outline  C...

                             vteTelecommunications.1
0  Beacon Broadcasting Cable protection system Ca...
1  Nasir Ahmed Edwin Howard Armstrong Mohamed M. ...
2  Coaxial cable Fiber-optic communication optica...
3  Bandwidth Links Network switching circuit pack...
4  Space-division Frequency-division Time-divisio...
5  Communication protocol Computer network Data t...
6  Cellular network Ethernet ISDN LAN Mobile NGN ...
7  ARPANET BITNET CYCLADES FidoNet Internet Inter...
8  Africa Americas North South Antarctica Asia Eu...
9  Telecommunication portal  Category  Outline  C...  ]

In [14]:
df = tables[0]
df.head()

,MCC,MNC,Brand,Operator,Status,Bands (MHz),References and notes
0,1,1,TEST,Test network,Operational,any,NaN
1,1,1,TEST,Test network,Operational,any,NaN
2,999,99,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"
3,999,999,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"

In [15]:
len(tables)

5

In [16]:
for i, table in enumerate(tables):
    print(f"Table {i}:")
    print(table.head())

Table 0:
   MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any
1    1    1  TEST  Test network  Operational         any
2  999   99   NaN  Internal use  Operational         any
3  999  999   NaN  Internal use  Operational         any

                              References and notes
0                                              NaN
1                                              NaN
2  Internal use in private networks, no roaming[6]
3  Internal use in private networks, no roaming[6]
Table 1:
   Mobile country code                                    Country ISO 3166  \
0                  289                                 A Abkhazia    GE-AB
1                  412                                Afghanistan       AF
2                  276                                    Albania       AL
3                  603                                    Algeria       DZ
4                  544  American Samoa (United States of America)       AS

                             Mobile network codes National MNC authority  \
0        List of mobile network codes in Abkhazia                    NaN
1     List of mobile network codes in Afghanistan                    NaN
2         List of mobile network codes in Albania                    NaN
3         List of mobile network codes in Algeria                    NaN
4  List of mobile network codes in American Samoa                    NaN

                    Remarks
0  MCC is not listed by ITU
1                       NaN
2                       NaN
3                       NaN
4                       NaN
Table 2:
   MCC  MNC    Brand                  Operator       Status Bands (MHz)  \
0  901    1      NaN                   Webbing      Unknown        MVNO
1  901    2      NaN            GlobalmatiX AG      Unknown     Unknown
2  901    3  Iridium                       NaN  Operational   Satellite
3  901    4      NaN  BBIX Singapore Pte. Ltd.      Unknown     Unknown
4  901    5      NaN      Thuraya RMSS Network  Operational   Satellite

                                References and notes
0            Former ICO Satellite Management[51][52]
1  Former Sense Communications International; veh...
2                                                NaN
3                              Former Globalstar[54]
4                                                NaN
Table 3:
   MCC  MNC     Brand                 Operator       Status Bands (MHz)  \
0  995    1  FonePlus  Sure (Diego Garcia) Ltd  Operational     GSM 900

                                References and notes
0  There appears to be no officially assigned MCC...
Table 4:
            vteTelecommunications  \
0                         History
1                        Pioneers
2              Transmission media
3  Network topology and switching
4                    Multiplexing

                             vteTelecommunications.1
0  Beacon Broadcasting Cable protection system Ca...
1  Nasir Ahmed Edwin Howard Armstrong Mohamed M. ...
2  Coaxial cable Fiber-optic communication optica...
3  Bandwidth Links Network switching circuit pack...
4  Space-division Frequency-division Time-divisio...

### Extracting a Specific HTML Table Using Match and Header

In [17]:
df = pd.read_html(
    url3,
    match="Country",
    header=0,
    storage_options={"User-Agent": "Mozilla/5.0"}
)[0]

df

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

## Reading Data from an Excel File

In [18]:
df_excel = pd.read_excel("razorpay.xlsx")
df_excel

,Shortlist,S. No.,University Roll No.,Name of Students,Branch,Email ID,Students' Mobile No.,10th%,12th %,B.Tech till\nnow
0,Yes,1,2201330120002,Aanya Goel,Computer Science,aanyagoel0106@gmail.com,9389210946,92.0,90.60,82.9
1,Yes,2,2201330120016,Amritanshu Srivastava,Computer Science,sriamrit7702@gmail.com,8987012898,90.0,85.00,86.4
2,Yes,6,2201330120030,Arshia Talwar,Computer Science,0221cs168@niet.co.in,9350105398,94.2,90.20,83.2
3,Yes,7,2201330120031,Aryan Kumar Choudhary,Computer Science,aryanchoudhary7050@gmail.com,7050677520,85.5,88.20,81.2
4,Yes,9,2201330120042,Devansh Prakash,Computer Science,devanshprakash02@gmail.com,8789543609,92.5,88.66,89.6
...,...,...,...,...,...,...,...,...,...,...
108,Yes,274,2201330310054,Indresh Jadaun,IT,indreshjadaun999@gmail.com,8433443015,94.4,96.20,87.7
109,Yes,276,2201330130067,Ayushi Verma,IT,abayushi6267@gmail.com,9644903690,95.0,87.40,84.9
110,Yes,283,2201330130118,Mohd Rayyan,IT,mr.rayyan2005@gmail.com,9897700760,95.0,92.00,87.3
111,Yes,284,2201330130120,Nafreen Anjum,IT,nafreenanjum23@gmail.com,9971025340,85.6,89.00,84.3
112,Yes,285,2201330130121,Nagesh Rathore,IT,0221ITE281@niet.co.in,9319372239,90.0,88.00,88.8

## Pickle File

Pickling is the process of converting a Python object (such as a list, dictionary, or class object) into a byte stream so that it can be saved to a file or transmitted over a network.

### Saving DataFrame as a Pickle File

In [19]:
df_excel.to_pickle('df_excel')
print(pd)

<module 'pandas' from 'd:\\python-tutorial\\venv\\Lib\\site-packages\\pandas\\__init__.py'>

In [20]:
pd.read_pickle('df_excel')

,Shortlist,S. No.,University Roll No.,Name of Students,Branch,Email ID,Students' Mobile No.,10th%,12th %,B.Tech till\nnow
0,Yes,1,2201330120002,Aanya Goel,Computer Science,aanyagoel0106@gmail.com,9389210946,92.0,90.60,82.9
1,Yes,2,2201330120016,Amritanshu Srivastava,Computer Science,sriamrit7702@gmail.com,8987012898,90.0,85.00,86.4
2,Yes,6,2201330120030,Arshia Talwar,Computer Science,0221cs168@niet.co.in,9350105398,94.2,90.20,83.2
3,Yes,7,2201330120031,Aryan Kumar Choudhary,Computer Science,aryanchoudhary7050@gmail.com,7050677520,85.5,88.20,81.2
4,Yes,9,2201330120042,Devansh Prakash,Computer Science,devanshprakash02@gmail.com,8789543609,92.5,88.66,89.6
...,...,...,...,...,...,...,...,...,...,...
108,Yes,274,2201330310054,Indresh Jadaun,IT,indreshjadaun999@gmail.com,8433443015,94.4,96.20,87.7
109,Yes,276,2201330130067,Ayushi Verma,IT,abayushi6267@gmail.com,9644903690,95.0,87.40,84.9
110,Yes,283,2201330130118,Mohd Rayyan,IT,mr.rayyan2005@gmail.com,9897700760,95.0,92.00,87.3
111,Yes,284,2201330130120,Nafreen Anjum,IT,nafreenanjum23@gmail.com,9971025340,85.6,89.00,84.3
112,Yes,285,2201330130121,Nagesh Rathore,IT,0221ITE281@niet.co.in,9319372239,90.0,88.00,88.8